AWSTemplateFormatVersion: "2010-09-09"
Description: "code bucket for data pipeline"


Parameters:

  appName:
    Type: "String"
    Default: "workshop"

  environment:
    Type: "String"
    Default: "dev"


Resources:

  sourceBucket:
    Type: "AWS::S3::Bucket"
    Description: "code bucket for data pipeline"
    Properties:
      BucketName: !Sub "${appName}-${environment}-${AWS::AccountId}--code"